name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml build

      - name: Run tests
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml run api dotnet test

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml up -d

  deploy_production:
    runs-on: ubuntu-latest
    needs: deploy_staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml up -d
